### ISSUE TITLE
<BinaCPP::get_depth> Segmentation fault

### ISSUE THREAD

**Issue by Exteroqs** [binance-exchange/binacpp#19]
I have this problem <BinaCPP::get_depth> Segmentation fault.
My code is:
Json::Value resulta;
BinaCPP::get_depth( "NCASHETH", 5, resulta ) ;
cout << resulta << endl;

I get:
2018-03-10 21:03:32 936921 :<BinaCPP::get_depth>
Segmentation fault

I got the same problem with BinaCPP::get_order().

I do not know if it's a bug or it's a problem of mine, but the other functions , BinaCPP::get_price() and BinaCPP::get_24hr() work fine for me. The others that I have not tried yet.
I use these library versions and I compile in linux 64bit:
-libcurl 7.47
-libwebsockets-2.4.2
-jsoncpp-1.8.4

**Comment by tensaix2j** [comment]
I figured out that it is caused by to_string override, I have made some changes on https://github.com/binance-exchange/binacpp/commit/910c004a76509c575e1f6842e42c2dabbc6f1d37

Goto src folder recompile the src by typing: make -B
and then goto example folder to recompile the example by typing: make -B example 

it shd work now.

**Comment by Exteroqs** [comment]
work fine now, 
also I feel  now a bit more fast the query of the others functions . 
thank very much.
